project_id = "ltwxqgvoskajqpspizsd"

[functions.search-leads]
verify_jwt = false

[functions.generate-approach]
verify_jwt = false

[functions.search-representatives]
verify_jwt = false

[functions.search-suppliers]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false
