// Customer types / business segments - extracted from Configuration.tsx for performance
// This file is loaded once at module level, preventing re-creation on every render

export const CUSTOMER_TYPES: string[] = [
  "Restaurantes",
  "Pizzarias",
  "Padarias",
  "Bares",
  "Lanchonetes",
  "Supermercados",
  "Hipermercados",
  "Mercados",
  "Mercearias",
  "Atacadistas de Alimentos",
  "Distribuidores de Alimentos",
  "Distribuidores de Food Service",
  "Cestas Básicas",
  "Confeitarias",
  "Docerias",
  "Salgadeiros",
  "Empresas de Gulla",
  "Pastelarias",
  "Hamburguerias",
  "Esfiharias",
  "Hot Dogs",
  "Food Trucks",
  "Churrascarias",
  "Catering",
  "Casas de Massas",
  "Indústrias de Alimentos",
  "Granjas",
  "Lojas de Pneus",
  "Lojas de Rodas Esportivas",
  "Cozinhas Industriais",
  "Indústrias de Biscoitos",
  "Distribuidoras de Doces",
  "Indústrias de Produtos Pet",
  "Agência de Eventos",
  "Distribuidores de Frios",
  "Farmácias",
  "Lojas de Roupas",
  "Salões de Beleza",
  "Escritórios",
  "Materiais de Construção",
  "Lojas de Materiais Elétricos",
  "Agropecuária",
  "E-commerce",
  "Lojas de Ferramentas",
  "Chaveiros",
  "Indústrias de Pão de Queijo",
  "Escolinhas de Futebol",
  "Escolinhas de Basquete",
  "Escolinhas de Natação",
  "Escolinhas de Artes Marciais",
  "Arenas de Beach Tennis",
  "Quadras de Tênis",
  "Clubes Esportivos",
  "Confecções",
  "Lojas de Tecidos",
  "Lojas de Tecidos para Decoração",
  "Ateliês de Costura",
  "Indústrias Têxteis",
  "Bordados",
  "Lojas de Aviamentos",
  "Malharias",
  "Fábricas de Uniformes",
  "Lojas de Tapeçaria, Cortinas e Persianas",
  "Transportadoras",
  "Frotistas",
  "Empresas com Frota Própria",
  "Vans Escolares",
  "Táxis e Cooperativas",
  "Motoristas de Aplicativo",
  "Empresas de Logística",
  "Locadoras de Veículos",
  "Empresas de Turismo",
  "Clínicas Médicas",
  "Clínicas Odontológicas",
  "Hospitais",
  "Laboratórios",
  "Clínicas de Fisioterapia",
  "Ortopedias",
  "Distribuidoras de Produtos Hospitalares",
  "Planos de Saúde",
  "Home Care",
  "Clínicas de Psicologia",
  "Nutricionistas",
  "Fonoaudiólogos",
  "Gráficas",
  "Comunicação Visual",
  "Impressão Digital",
  "Agências de Publicidade",
  "Estúdios de Design",
  "Produtoras de Conteúdo",
  "Lojas de Sinalização",
  "Serigrafias",
  "Estamparias",
  "Fábricas de Embalagens",
  "Distribuidoras de Embalagens",
  "Editoras",
  "Construtoras",
  "Empreiteiras",
  "Incorporadoras",
  "Arquitetos",
  "Escritórios de Arquitetura",
  "Marmorarias",
  "Vidraçarias",
  "Serralherias",
  "Imobiliárias",
  "Gesseiros",
  "Fabricantes de Esquadrias de Alumínio",
  "Fabricantes de Esquadrias de Madeira",
  "Lojas de Revestimentos",
  "Lojas de Portas",
  "Indústrias de Eletrônica",
  "Indústrias Automotivas",
  "Indústrias de Automação",
  "Indústrias de Iluminação e LED",
  "Montadores de Painel Elétrico",
  "Empresas de Automação Industrial",
  "Instaladores Elétricos",
  "Empresas de Manutenção Elétrica",
  "Empresas de Energia Solar",
  "Indústrias que Montam ou Reformam Painéis",
  "Metalúrgicas",
  "Siderúrgicas",
  "Empresas de Solda",
  "Caldeirarias",
  "Usinagens",
  "Estruturas Metálicas",
  "Fabricantes de Máquinas e Equipamentos",
  "Distribuidores de Aço e Ferro",
  "Distribuidores de Material Médico Hospitalar",
  "Distribuidores de Pêssegos",
  "Indústrias Mecânicas",
  "Indústrias de Plásticos",
  "Indústrias Químicas",
  "Indústrias de Papel e Celulose",
  "Indústrias de Borracha",
  "Indústrias de Vidro",
  "Indústrias de Cerâmica",
  "Indústrias de Cosméticos",
  "Indústrias Farmacêuticas",
  "Indústrias de Bebidas",
  "Indústrias de Embalagens",
  "Indústrias de Móveis",
  "Indústrias de Calçados",
  "Indústrias de Tintas",
  "Indústrias de Fertilizantes",
  "Indústrias de Ração Animal",
  "Indústrias de Produtos de Limpeza",
  "Indústrias de Papel Higiênico e Descartáveis",
  "Indústrias Gráficas",
  "Indústrias de Componentes Eletrônicos",
  "Indústrias de Fios e Cabos",
  "Lojas de Produtos Naturais",
  "Empórios Naturais",
  "Lojas de Suplementos",
  "Hortifrútis",
  "Lojas Veganas",
  "Academias",
  "Clínicas de Estética",
  "Spas",
  "Pet Shops",
  "Loja de Ração Pet",
  "Fabricantes de Ração Pet",
  "Banho e Tosa",
  "Hotéis Pet",
  "Creches Pet",
  "Adestramento de Animais",
  "Clínicas Veterinárias",
  "Abatedouros de Aves",
  "Abatedouros de Bovinos",
  "Abatedouros de Suínos",
  "Abatedouros e Frigoríficos",
  "Oficinas Mecânicas",
  "Autopeças",
  "Distribuidores de Autopeças",
  "Postos de Combustível",
  "Hotéis e Pousadas",
  "Escolas e Cursos",
  "Papelarias",
  "Óticas",
  "Joalherias",
  "Lojas de Cama, Mesa e Banho",
  "Lojas de Utilidades Domésticas",
  "Distribuidores de Água",
  "Distribuidores de Refrigerantes",
  "Distribuidores de Cervejas",
  "Artigos de Caça, Pesca e Camping",
  "Cartonagem",
  "Restaurantes Japoneses",
  "Sushi Bars",
  "Restaurantes Orientais",
  "Restaurantes Chineses",
  "Temakerias",
  "Lojas de Presentes de Alto Padrão",
  "Perfumarias",
  "Restaurantes Premium",
  "Buffets de Festas",
  "Empresas de Locação de Materiais para Eventos",
  "Indústrias de Mineração",
  "Indústrias Sucroalcooleiras",
  "Autopeças de Vans e Utilitários",
  "E-commerces de Peças Automotivas",
  "E-commerces de Utilidades Domésticas",
  "E-commerces de Perfumaria e Casa",
  "E-commerces de Sabonetes",
  "E-commerces de Presentes Finos",
  "Lojas de Moda Infantil",
  "Lojas de Móveis",
  "Lojas de Variedades",
  "Lojas de Material Esportivo",
  "Lojas de Celular",
  "Lojas de Bicicleta",
  "Lojas de Veículos Elétricos",
  "Lojas de Autopropelidos",
  "Lojas de Moto",
  "Lojas de Carro",
  "Concessionárias",
  "Lojas de Informática",
  "Lojas de Calçados",
  "Lojas de Bolsas e Acessórios",
  "Lojas de Brinquedos",
  "Lojas de Colchões",
  "Lojas de Eletrodomésticos",
  "Lojas de Cosméticos",
  "Floriculturas",
  "Livrarias",
  "Lavanderias",
  "Açougues",
  "Peixarias",
  "Barbearias",
  "Estúdios de Tatuagem",
  "Sorveterias",
  "Cafeterias",
  "Cervejarias Artesanais",
  "Tabacarias",
  "Lojas de Artigos para Festas",
  "Corretoras de Seguros",
  "Escritórios de Contabilidade",
  "Escritórios de Advocacia",
  "Escolas de Idiomas",
  "Escolas de Música",
  "Autoescolas",
  "Lava-Rápidos",
  "Funilarias e Pinturas",
  "Auto Elétricas",
  "Borracharias",
  "Empresas de Segurança",
  "Empresas de Limpeza",
  "Dedetizadoras",
  "Coworkings",
  "Casas de Festas",
  "Lojas de Artigos para Piscina",
  "Lojas de Artigos Religiosos",
  "Adegas e Distribuidoras de Vinhos",
  "Casas Lotéricas",
  "Cartórios",
  "Despachantes",
  "Estacionamentos",
  "Funerárias",
  "Casas de Repouso",
  "Creches e Berçários",
  "Escolas Particulares",
  "Faculdades e Universidades",
  "Cursos Técnicos e Profissionalizantes",
  "Consultorias Empresariais",
  "Agências de Viagens",
  "Casas de Câmbio",
  "Financeiras e Crédito",
  "Cooperativas de Crédito",
  "Seguradoras",
  "Lotéricas e Correspondentes Bancários",
  "Empresas de Contêineres e Módulos",
  "Empresas de Mudanças",
  "Guardas-Móveis",
  "Empresas de Reciclagem",
  "Sucateiros",
  "Ferro-Velhos",
  "Lojas de EPI",
  "Distribuidoras de Gases Industriais",
  "Empresas de Ar Condicionado",
  "Empresas de Elevadores",
  "Empresas de Impermeabilização",
  "Empresas de Desentupimento",
  "Empresas de Paisagismo e Jardinagem",
  "Empresas de Steel Frame",
  "Construtoras de Pré-Moldado",
  "Sistemas de Incêndio",
  "Engenharias",
  "Clínicas de Dermatologia",
  "Clínicas de Oftalmologia",
  "Clínicas de Cardiologia",
  "Clínicas de Pediatria",
  "Clínicas de Ginecologia",
  "Clínicas de Urologia",
  "Clínicas de Ortopedia",
  "Clínicas de Neurologia",
  "Dentistas e Consultórios Odontológicos",
  "Próteses Dentárias",
  "Laboratórios de Prótese Dentária",
  "Distribuidoras de Produtos Odontológicos",
  "Depósitos de Materiais de Construção",
  "Lojas de Tintas",
  "Lojas de Pisos e Azulejos",
  "Lojas de Iluminação",
  "Lojas de Lustres e Luminárias",
  "Lojas de Decoração",
  "Design de Interiores",
  "Paisagismo e Jardinagem",
  "Viveiros de Plantas",
  "Garden Centers",
  "Casas Agropecuárias",
  "Cooperativas Agrícolas",
  "Revendas de Insumos Agrícolas",
  "Revendas de Máquinas Agrícolas",
  "Tratores e Implementos Agrícolas",
  "Irrigação",
  "Silos e Armazéns",
  "Frigoríficos",
  "Laticínios",
  "Queijarias",
  "Cervejarias",
  "Vinícolas",
  "Destilarias",
  "Torrefadoras de Café",
  "Empresas de Climatização",
  "Empresas de Refrigeração Industrial",
  "Empresas de Ventilação Industrial",
  "Empresas de Caldeiras e Vapor",
  "Empresas de Compressores",
  "Empresas de Bombas Hidráulicas",
  "Empresas de Tratamento de Água",
  "Empresas de Saneamento",
  "Empresas de Gestão de Resíduos",
  "Empresas de Coleta de Lixo",
  "Empresas de Terraplanagem",
  "Empresas de Pavimentação",
  "Concreteiras",
  "Usinas de Asfalto",
  "Pedras e Mármores",
  "Granitos",
  "Lojas de Artigos de Pesca",
  "Casas de Armas e Munições",
  "Estandes de Tiro",
  "Casas de Câmbio e Remessas",
  "Seguros de Vida e Previdência",
  "Corretoras de Imóveis",
  "Administradoras de Condomínios",
  "Empresas de Portaria e Zeladoria",
  "Academias de Dança",
  "Escolas de Teatro",
  "Estúdios de Pilates",
  "Estúdios de Yoga",
  "Estúdios de Fotografia",
  "Produtoras de Vídeo",
  "Estúdios de Gravação",
  "Gráficas Rápidas",
  "Copiadora e Impressão",
  "Lojas de Artesanato",
  "Lojas de Aviamentos e Armarinhos",
  "Antiquários",
  "Brechós",
  "Lojas de Instrumentos Musicais",
  "Lojas de Som e Acessórios Automotivos",
  "Empresas de Rastreamento Veicular",
  "Empresas de Blindagem",
  "Retíficas de Motores",
  "Autovidros",
  // --- Comércio e Varejo ---
  "Lojas de Perfumes Importados",
  "Lojas de Produtos de Limpeza",
  "Lojas de Produtos para Cabelo",
  "Lojas de Maquiagem",
  "Lojas de Suplementos Esportivos",
  "Lojas de Produtos Orgânicos",
  "Lojas de Produtos sem Glúten",
  "Lojas de Bebidas",
  "Lojas de Vinhos",
  "Lojas de Cervejas Artesanais",
  "Lojas de Café Gourmet",
  "Lojas de Chás e Especiarias",
  "Lojas de Produtos Árabes",
  "Lojas de Produtos Orientais",
  "Lojas de Conveniência",
  "Lojas de Produtos para Piscina",
  "Lojas de Produtos de Segurança",
  "Lojas de Câmeras e Alarmes",
  "Lojas de Equipamentos de Proteção",
  "Lojas de Equipamentos de Ginástica",
  "Lojas de Produtos para Camping",
  "Lojas de Malas e Mochilas",
  "Lojas de Artigos Militares",
  "Lojas de Óculos de Sol",
  "Lojas de Relógios",
  "Lojas de Semijoias",
  "Lojas de Bijuterias",
  "Lojas de Artigos para Bebê",
  "Lojas de Fraldas",
  "Lojas de Produtos para Gestantes",
  "Lojas de Artigos para Aniversário",
  "Lojas de Balões",
  "Lojas de Embalagens para Presentes",
  "Lojas de Artigos de Papelaria Fina",
  "Lojas de Material de Escritório",
  "Lojas de Móveis para Escritório",
  "Lojas de Informática e Periféricos",
  "Lojas de Games e Videogames",
  "Lojas de Drones",
  "Lojas de Aeromodelismo",
  "Lojas de Som Profissional",
  "Lojas de Equipamentos de DJ",
  "Lojas de Artigos para Churrasco",
  "Lojas de Lareiras e Aquecedores",
  "Lojas de Ar Condicionado",
  "Lojas de Geradores",
  "Lojas de Ferragens",
  "Lojas de Parafusos",
  "Lojas de Rolamentos",
  "Lojas de Correias e Mangueiras",
  // --- Alimentação e Gastronomia ---
  "Açaiterias",
  "Casas de Açaí",
  "Creperies",
  "Tapiocarias",
  "Casas de Sucos",
  "Smoothie Bars",
  "Restaurantes Veganos",
  "Restaurantes Vegetarianos",
  "Restaurantes Fit",
  "Restaurantes Self-Service",
  "Restaurantes Italianos",
  "Restaurantes Mexicanos",
  "Restaurantes Indianos",
  "Restaurantes Tailandeses",
  "Restaurantes Coreanos",
  "Restaurantes Peruanos",
  "Restaurantes Árabes",
  "Restaurantes Portugueses",
  "Restaurantes de Frutos do Mar",
  "Marisquerias",
  "Casas de Crepe",
  "Casas de Waffle",
  "Casas de Fondue",
  "Espetarias",
  "Casas de Feijoada",
  "Restaurantes por Quilo",
  "Marmitarias",
  "Quentinhas e Marmitas",
  "Restaurantes de Comida Baiana",
  "Restaurantes de Comida Mineira",
  "Restaurantes de Comida Nordestina",
  "Restaurantes de Comida Gaúcha",
  "Padarias Artesanais",
  "Pâtisseries",
  "Chocolaterias",
  "Gelatarias",
  "Frozen Yogurts",
  "Bubble Tea",
  "Poké Bowls",
  "Açougues Gourmet",
  "Empórios Gourmet",
  "Delicatessens",
  "Rotisseries",
  "Casas de Carnes",
  "Casas de Frangos",
  "Distribuidoras de Carnes",
  "Distribuidoras de Peixes",
  "Distribuidoras de Congelados",
  "Distribuidoras de Sorvetes",
  "Distribuidoras de Açaí",
  "Distribuidoras de Polpas de Frutas",
  "Distribuidoras de Ovos",
  "Distribuidoras de Queijos",
  "Distribuidoras de Embutidos",
  // --- Indústria e Manufatura ---
  "Indústrias de Alimentos Congelados",
  "Indústrias de Conservas",
  "Indústrias de Massas",
  "Indústrias de Temperos e Condimentos",
  "Indústrias de Molhos",
  "Indústrias de Laticínios",
  "Indústrias de Sorvetes",
  "Indústrias de Chocolates",
  "Indústrias de Balas e Guloseimas",
  "Indústrias de Salgadinhos",
  "Indústrias de Café",
  "Indústrias de Chá e Ervas",
  "Indústrias de Sucos e Polpas",
  "Indústrias de Água Mineral",
  "Indústrias de Refrigerantes",
  "Indústrias de Cervejas",
  "Indústrias de Cachaça",
  "Indústrias de Vinagres",
  "Indústrias de Óleos e Azeites",
  "Indústrias de Farinhas",
  "Indústrias de Açúcar",
  "Indústrias de Arroz",
  "Indústrias de Feijão",
  "Indústrias de Carvão",
  "Indústrias de Gelo",
  "Indústrias de Velas",
  "Indústrias de Sabão e Sabonetes",
  "Indústrias de Detergentes",
  "Indústrias de Perfumes",
  "Indústrias de Fraldas Descartáveis",
  "Indústrias de Colchões",
  "Indústrias de Estofados",
  "Indústrias de Espumas",
  "Indústrias de Travesseiros",
  "Indústrias de Vassouras e Escovas",
  "Indústrias de Cordas e Barbantes",
  "Indústrias de Redes e Telas",
  "Indústrias de Arames",
  "Indústrias de Pregos e Parafusos",
  "Indústrias de Tubos e Conexões",
  "Indústrias de PVC",
  "Indústrias de Fibra de Vidro",
  "Indústrias de Acrílico",
  "Indústrias de Isopor",
  "Indústrias de Sacolas Plásticas",
  "Indústrias de Sacos de Lixo",
  "Indústrias de Descartáveis Plásticos",
  "Indústrias de Brinquedos",
  "Indústrias de Joias",
  "Indústrias de Bijuterias",
  "Indústrias de Botões e Zíperes",
  "Indústrias de Etiquetas e Rótulos",
  "Indústrias de Fitas Adesivas",
  "Indústrias de Caixas de Papelão",
  "Indústrias de Paletes",
  "Indústrias de Compensados",
  "Indústrias de MDF e MDP",
  "Indústrias de Portas e Janelas",
  "Indústrias de Telhas",
  "Indústrias de Blocos e Tijolos",
  "Indústrias de Argamassa",
  "Indústrias de Impermeabilizantes",
  "Indústrias de Resinas",
  "Indústrias de Adesivos e Colas",
  "Indústrias de Tintas Automotivas",
  "Indústrias de Vernizes e Solventes",
  "Indústrias de Lubrificantes",
  "Indústrias de Baterias",
  "Indústrias de Transformadores",
  "Indústrias de Motores Elétricos",
  "Indústrias de Geradores",
  "Indústrias de Painéis Solares",
  "Indústrias de Implementos Agrícolas",
  "Indústrias de Silos",
  "Indústrias de Tanques",
  "Indústrias de Equipamentos de Laboratório",
  "Indústrias de Instrumentos de Medição",
  "Indústrias de Equipamentos Hospitalares",
  "Indústrias de Próteses",
  // --- Saúde e Bem-estar ---
  "Clínicas de Endocrinologia",
  "Clínicas de Gastroenterologia",
  "Clínicas de Pneumologia",
  "Clínicas de Reumatologia",
  "Clínicas de Oncologia",
  "Clínicas de Hematologia",
  "Clínicas de Nefrologia",
  "Clínicas de Otorrinolaringologia",
  "Clínicas de Proctologia",
  "Clínicas de Geriatria",
  // --- Serviços ---
  "Empresas de TI",
  "Empresas de Software",
  "Empresas de Desenvolvimento Web",
  "Empresas de Marketing Digital",
  "Empresas de SEO",
  "Empresas de Tráfego Pago",
  "Empresas de Social Media",
  "Empresas de E-mail Marketing",
  "Agências de Comunicação",
  "Agências de RP",
  "Agências de Branding",
  "Agências de Design Gráfico",
  "Agências de Eventos Esportivos",
  "Agências de Eventos Corporativos",
  "Agências de Festas Corporativas",
  "Agências de Marketing Esportivo",
  "Agências de Influenciadores",
  "Agências de Formaturas",
  "Agências de Propaganda",
  "Agências de Turismo Religioso",
  "Agências de Turismo Cultural",
  "Agências de Shows",
  // --- Tecnologia ---
  "Empresas de Telecomunicações",
  "Empresas de Internet",
  "Provedores de Internet",
  "Empresas de Fibra Óptica",
  "Empresas de CFTV",
  "Empresas de Automação Residencial",
  "Empresas de Controle de Acesso",
  "Empresas de Alarmes",
  // --- Educação ---
  "Escolas de Informática",
  "Escolas de Robótica",
  "Escolas de Programação",
  "Escolas de Culinária",
  "Escolas de Gastronomia",
  "Escolas de Aviação",
  "Escolas de Náutica",
  "Escolas de Mergulho",
  // --- Automotivo ---
  "Empresas de Estética Automotiva",
  "Empresas de Polimento",
  "Empresas de Insulfilm",
  "Empresas de Envelopamento",
  "Empresas de Acessórios Automotivos",
  "Distribuidores de Lubrificantes",
  "Distribuidores de Filtros",
  "Distribuidores de Pneus",
  "Distribuidores de Baterias",
  // --- Agro ---
  "Pecuária de Corte",
  "Pecuária de Leite",
  "Avicultura",
  "Suinocultura",
  "Apicultura",
  "Aquicultura",
  "Piscicultura",
  "Floricultura",
  "Fruticultura",
  "Horticultura",
  "Silvicultura",
  "Cafeicultura",
  // --- Construção ---
  "Empresas de Drywall",
  "Empresas de Gesso",
  "Empresas de Pintura Predial",
  "Empresas de Limpeza Predial",
  "Empresas de Manutenção Predial",
  "Empresas de Demolição",
  "Empresas de Escavação",
  "Empresas de Fundações",
  "Empresas de Estruturas de Concreto",
  "Empresas de Alvenaria",
  // --- Diversos ---
  "Distribuidores de Materiais Elétricos",
  "Distribuidores de Ferramentas",
  "Distribuidores de EPI",
  "Distribuidores de Materiais Hidráulicos",
  "Distribuidores de Produtos de Limpeza",
  "Distribuidores de Cosméticos",
  "Distribuidores de Bebidas",
  "Distribuidores de Doces e Balas",
  "Distribuidores de Brinquedos",
  "Distribuidores de Papelaria",
  "Distribuidores de Embalagens Plásticas",
  "Distribuidores de Descartáveis",
  "Distribuidores de Produtos Químicos",
  "Distribuidores de Tintas",
  "Distribuidores de Madeira",
  // --- Metalurgia Avançada ---
  "Fundições de Alumínio",
  "Fundições de Bronze",
  "Fundições de Ferro",
  "Fundições de Aço",
  "Forjarias",
  "Trefilarias",
  "Laminadoras",
  "Estamparias de Metal",
  "Galvanoplastias",
  "Empresas de Tratamento Térmico",
  "Empresas de Jateamento",
  "Empresas de Cromagem",
  "Empresas de Zincagem",
  "Empresas de Anodização",
  // --- Naval e Aeroespacial ---
  "Estaleiros",
  "Marinas",
  "Empresas de Manutenção Naval",
  "Empresas de Manutenção Aeronáutica",
  "Hangares",
  "Empresas de Peças Aeronáuticas",
  // --- Automação Industrial ---
  "Empresas de CLP e SCADA",
  "Empresas de Robótica Industrial",
  "Empresas de Instrumentação",
  "Empresas de Pneumática",
  "Empresas de Hidráulica Industrial",
  "Empresas de Válvulas Industriais",
  "Empresas de Engrenagens",
  "Empresas de Redutores",
  "Empresas de Acoplamentos",
  "Empresas de Mancais",
  // --- Têxtil e Confecções ---
  "Tecelagens",
  "Fiações",
  "Tinturarias Industriais",
  "Lavanderias Industriais",
  "Fábricas de Meias",
  "Fábricas de Lingerie",
  "Fábricas de Moda Praia",
  "Fábricas de Moda Fitness",
  "Fábricas de Jeans",
  "Fábricas de Camisetas",
  "Fábricas de Bonés",
  "Fábricas de Bolsas",
  "Fábricas de Calçados Esportivos",
  "Fábricas de Calçados de Segurança",
  "Fábricas de Sandálias",
  // --- Plásticos e Embalagens ---
  "Empresas de Injeção Plástica",
  "Empresas de Sopro Plástico",
  "Empresas de Termoformagem",
  "Empresas de Rotomoldagem",
  "Empresas de Extrusão de Plásticos",
  "Empresas de Reciclagem de Plásticos",
  "Empresas de Embalagens Flexíveis",
  "Empresas de Embalagens Rígidas",
  "Empresas de Sacolas Ecológicas",
  // --- Sustentabilidade e ESG ---
  "Empresas de Energia Eólica",
  "Empresas de Biomassa",
  "Empresas de Biogás",
  "Empresas de Compostagem",
  "Empresas de Consultoria Ambiental",
  "Empresas de Licenciamento Ambiental",
  "Empresas de Remediação de Solo",
  "Empresas de Créditos de Carbono",
  "Empresas de Economia Circular",
  // --- Cannabis Legal ---
  "Clínicas de Cannabis Medicinal",
  "Lojas de CBD",
  "Fabricantes de Produtos de CBD",
  // --- Economia Compartilhada ---
  "Espaços de Coworking",
  "Espaços de Coliving",
  "Lavanderias Compartilhadas",
  "Cozinhas Compartilhadas",
  "Dark Kitchens",
  "Cloud Kitchens",
  // --- E-sports e Gaming ---
  "Arenas de E-sports",
  "Lojas de PC Gamer",
  "Lojas de Periféricos Gamer",
  "Estúdios de Streaming",
  // --- Serviços para Idosos ---
  "Residenciais para Idosos",
  "Centros Dia para Idosos",
  "Home Care para Idosos",
  "Empresas de Cuidadores",
  // --- Franquias ---
  "Franquias de Alimentação",
  "Franquias de Açaí",
  "Franquias de Sorvete",
  "Franquias de Pizza",
  "Franquias de Hambúrguer",
  "Franquias de Café",
  "Franquias de Suco",
  "Franquias de Beleza",
  "Franquias de Estética",
  "Franquias de Limpeza",
  "Franquias de Educação",
  "Franquias de Idiomas",
  "Franquias de Saúde",
  "Franquias de Fitness",
  "Franquias de Pet",
  "Franquias de Tecnologia",
  "Franquias de Moda",
  "Franquias de Acessórios",
  // --- Varejo Avançado ---
  "Lojas de Moda Plus Size",
  "Lojas de Moda Sustentável",
  "Lojas de Moda Masculina",
  "Lojas de Moda Feminina",
  "Lojas de Moda Evangélica",
  "Lojas de Roupa de Cama",
  "Lojas de Tapetes",
  "Lojas de Cortinas",
  "Lojas de Persianas",
  "Lojas de Papel de Parede",
  "Lojas de Adesivos Decorativos",
  "Lojas de Quadros e Molduras",
  "Lojas de Espelhos",
  "Lojas de Artigos de Vidro",
  "Lojas de Artigos de Porcelana",
  "Lojas de Artigos de Cristal",
  // --- Tecnologia e IoT ---
  "Empresas de IoT",
  "Empresas de Inteligência Artificial",
  "Empresas de Blockchain",
  "Empresas de Cloud Computing",
  "Empresas de Segurança da Informação",
  "Empresas de Data Center",
  "Empresas de Backup e Recuperação",
  "Empresas de ERP",
  "Empresas de CRM",
  // --- Impressão e Sublimação ---
  "Empresas de Sublimação",
  "Empresas de DTG",
  "Empresas de Laser",
  "Empresas de CNC",
  "Empresas de Corte e Vinco",
  "Empresas de Plotagem",
  "Empresas de Impressão 3D",
  "Empresas de Gravação a Laser",
  "Empresas de Impressão em Canecas",
  "Empresas de Impressão em Couro",
  "Empresas de Impressão em Metal",
  "Empresas de Impressão em Tecido",
  "Empresas de Impressão em Vidro",
  "Empresas de Impressão UV",
  "Empresas de Personalização de Brindes",
  "Empresas de Personalização de Produtos",
  "Empresas de Transfer DTF",
].sort();
